Ecommerce/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('api/v1/', include('djoser.urls')),
    # path('api/v1/', include('djoser.urls.authtoken')),
    path('', include('orders.urls', namespace='orders')),
    path('', include('customers.urls',namespace='customers')),
    path('', include('products.urls',namespace='products')),

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

customers/urls.py
from django.urls import path


from .views import *
app_name = 'customers'

urlpatterns = [
    path('register/',UserRegisterView.as_view(),name='register'),
    path('login/', UserLoginView.as_view(), name='login'),
    path('logout/', UserLogoutView.as_view(), name='logout'),
    path('profile/', UserEditView.as_view(), name='profile'),
    path('changepassword/', change_password, name='changepassword'),

]

orders/urls.py
from django.urls import path
from .views import *


app_name = 'orders'



urlpatterns = [
    path('add-to-cart/',addtocart,name='addtocart'),
    path('cart/', viewcart, name='cart'),
    path('update-cart/',updatecart,name='updatecart'),
    path('delete-cart-item/',deletecartitem,name='deletecartitem'),
    path('add-to-wishlist/', addtowishlist, name='addtowishlist'),
    path('wishlist', wishlistview, name='wishlist'),
    path('delete-wishlist-item/',deletewishlistitem,name='deletewishlistitem'),
    path('checkout', checkout, name='checkout'),
    path('place-order', placeorder, name='placeorder'),
    path('my-orders', myorders, name='myorders'),
    path('orderview/<str:pk>/', orderview, name='orderview'),
    path('product-list/', productlist, name='productlist'),
    path('searchproduct/', searchproduct, name='searchproduct'),
    path('send-email/', send_email, name='sendemail'),
]

products/urls.py
from django.urls import path
app_name = 'products'

from .views import *

urlpatterns = [
    path('',HomeView.as_view(),name='home'),
    path('about/',AboutView.as_view(),name='about'),
    path('product/',ProductView.as_view(),name='product'),
    path('why/',WhyView.as_view(),name='why'),
    path('contact_us/',contact,name='contact_us'),
    path('<str:prod_slug>/', productview, name='product_detail'),
    path('category/<slug:slug>/', ProductView.as_view(), name='category_filter'),




]

templates/base/about.html
{% extends 'base/base.html' %}
{% load static %}
{% block title %}About{% endblock %}
  <!-- about section -->
{% block content %}
  <section class="about_section" id="about">
    <div class="container-fluid  ">
      <div class="row">
        <div class="col-md-5 ml-auto">
          <div class="detail-box pr-md-3">
            <div class="heading_container">
              <h2>
                We Provide Best For You
              </h2>
            </div>
            <p>
                Here is SADAF SHOP, your number one source for electronic devices. We're dedicated to giving you the very best of product, with a focus on three characteristics: dependability, customer service and uniqueness.
                We hope you enjoy our products as much as we enjoy offering them to you. If you have any questions or comments, please don't hesitate to contact us.
            </p>
            <a href="">
              Read More
            </a>
          </div>
        </div>
        <div class="col-md-6 px-0">
          <div class="img-box">
            <img src="{% static 'images/about-img.jpg'%}" alt="">
          </div>
        </div>
      </div>
    </div>
  </section>

  <!-- end about section -->



  <!-- end info_section -->

{% endblock %}

templates/base/base.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
  <!-- Basic -->
  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <!-- Mobile Metas -->
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
  <!-- Site Metas -->
  <link rel="icon" href="{% static 'images/fevicon.png'%}" type="image/gif" />
  <meta name="keywords" content="" />
  <meta name="description" content="" />
  <meta name="author" content="" />

  <title>{% block title %} {% endblock %}</title>


  <!-- bootstrap core css -->
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">
  <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.css'%}" >

  <!-- fonts style -->
  <link href="https://fonts.googleapis.com/css?family=Poppins:400,700&display=swap" rel="stylesheet"> <!-- range slider -->

  <!-- font awesome style -->
  <link href="{% static 'css/font-awesome.min.css'%}" rel="stylesheet" >

  <!-- Custom styles for this template -->
  <link href="{% static 'css/style.css'%}" rel="stylesheet" >
  <!-- responsive style -->
  <link href="{% static 'css/responsive.css'%}" rel="stylesheet" >
<link rel="stylesheet" href="//cdn.jsdelivr.net/npm/alertifyjs@1.13.1/build/css/alertify.min.css"/>
<!-- Default theme -->
<link rel="stylesheet" href="//cdn.jsdelivr.net/npm/alertifyjs@1.13.1/build/css/themes/default.min.css"/>
<link rel="stylesheet" href="//code.jquery.com/ui/1.13.2/themes/base/jquery-ui.css">
    <style>{% block style %}{% endblock %}</style>

    <meta name="referrer" content="no-referrer-when-downgrade">

</head>

<body>

  <div class="hero_area">
    <!-- header section strats -->
  {% include 'base/navbar.html' %}

{% block content %}

{% endblock %}

{% include 'base/footer.html' %}
</div>

  <!-- footer section -->
  <!-- jQery -->
  <script src="{% static '/js/jquery-3.4.1.min.js'%}"></script>
  <script  src="{% static '/js/custom.js'%}"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.bundle.min.js"></script>
<!--Start of Tawk.to Script-->
    <script type="text/javascript">
    var Tawk_API=Tawk_API||{}, Tawk_LoadStart=new Date();
    (function(){
    var s1=document.createElement("script"),s0=document.getElementsByTagName("script")[0];
    s1.async=true;
    s1.src='https://embed.tawk.to/62e8defc54f06e12d88c77a7/1g9eqe30g';
    s1.charset='UTF-8';
    s1.setAttribute('crossorigin','*');
    s0.parentNode.insertBefore(s1,s0);
    })();
    </script>
<!--End of Tawk.to Script-->
  <!-- bootstrap js -->
      <script src="{% static 'js/bootstrap.js'%}"></script>
  <!-- custom js -->
    <script src="https://code.jquery.com/ui/1.13.2/jquery-ui.js"></script>
  <script>
      var availableTags = [];

       $.ajax({
            method : 'GET',
            url : '/product-list/',
            success: function (response){

                startauto(response)

            }
        })

      function startauto(availableTags){

      $( "#searchproducts" ).autocomplete({
      source: availableTags
    });
       }
  </script>
    <script src="//cdn.jsdelivr.net/npm/alertifyjs@1.13.1/build/alertify.min.js"></script>

  <script>
  alertify.set('notifier','position', 'top-right');
      {% for msg in messages %}
          alertify.success('{{ msg }}',3);
      {% endfor %}


  </script>




</body>

</html>

templates/base/contact_us.html
{% extends 'base/base.html' %}
{% load static %}
{% block title %}Contact us{% endblock %}
  <!-- about section -->
{% block content %}
            <div class="section-header" style="margin-top: 30px;" id="contact">
            <div class="text-center">
           <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3240.0756977594074!2d51.3398935851632!3d35.69975478019!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3f8dfe05737fbcc9%3A0x274833de5c05c70c!2z2YXbjNiv2KfZhiDYotiy2KfYr9uM2Iwg2KrZh9ix2KfZhtiMINin24zYsdin2YY!5e0!3m2!1sfa!2s!4v1644267480334!5m2!1sfa!2s"
                   width="800" height="600" style="border:0;"  allowfullscreen="" loading="lazy" ></iframe> <br></div>
{#            <div style="text-align: center">#}
<div class="container" >
      <div class="row">
        <div class="col-lg-12">
          <div class="info_contact text-center">
            <h5>
              <a href="" class="navbar-brand">
                <span>
                  SADAF SHOP
                </span>
              </a>
            </h5>
            <p>
              <i class="fa fa-map-marker" aria-hidden="true"></i>
              Tehran Azadi Square
            </p>
            <p>
              <i class="fa fa-phone" aria-hidden="true"></i>
              09376051315
            </p>
            <p>
              <i class="fa fa-envelope" aria-hidden="true"></i>
              Alirezahn1@yahoo.com
            </p>
          </div>
        </div>
        </div>
            </div>
                <div class="row justify-content-center">
    <div class="col-md-6">
        <div class="card mt-3 shadow">
            <div class="card-body">
		<h3>Contact us directly if you have any questions or suggestions</h3>
                <hr>
		<p>
			One of our staff members will be happy to contact you directly and answer your questions as soon as possible.
		</p>
		<form method="post">
        {% csrf_token %}
             <div class="form-group col-md-6">
                <label for=""> First Name :</label>
                {{ form.first_name }}
                          {% if form.errors.first_name %}
                <label class="text-danger">{{ form.errors.first_name }}</label>
                {% endif %}
             </div>
            <div class="form-group col-md-6">
                <label for=""> Last Name :</label>
                {{ form.last_name }}
                                {% if form.errors.last_name %}
                <label class="text-danger">{{ form.errors.last_name }}</label>
                {% endif %}
            </div>
                             <div class="form-group col-md-6">
                <label for=""> Email :</label>
                {{ form.email }}
                         {% if form.errors.email %}
                <label class="text-danger">{{ form.errors.email }}</label>
                {% endif %}
            </div>
                                  <div class="form-group col-md-12">
                <label for=""> Message :</label>
                {{ form.message }}
                         {% if form.errors.message %}
                <label class="text-danger">{{ form.errors.message }}</label>
                {% endif %}
            </div>
             <button type="submit"  class="btn btn-primary float-right shadow px-4"> Send </button>
        </form>
    </div>
            </div>
    </div>
                </div>
            </div>



  <!-- end client section -->

 {% endblock %}

templates/base/footer.html
{% load static %}
<section class="info_section ">
    <div class="container">

      <div class="row">
        <div class="col-md-3">
          <div class="info_contact">
            <h5>
              <a href="{% url 'products:home' %}" class="navbar-brand">
                <span>
                  SADAF SHOP
                </span>
              </a>
            </h5>
            <p>
              <i class="fa fa-map-marker" aria-hidden="true"></i>
              Tehran Azadi Square
            </p>
            <p>
              <i class="fa fa-phone" aria-hidden="true"></i>
              09376051315
            </p>
            <p>
              <i class="fa fa-envelope" aria-hidden="true"></i>
              Alirezahn1@yahoo.com
            </p>
          </div>
        </div>
        <div class="col-md-3">
          <div class="info_info">
            <h5>
              Information
            </h5>
            <p>
                Here is SADAF SHOP, your number one source for electronic devices.
            </p>
          </div>
        </div>
        <div class="col-md-3">
          <div class="info_links">
            <h5>
              Useful Link
            </h5>
            <ul>
              <li>
                <a href="{% url 'products:home' %}">
                  Home
                </a>
              </li>
              <li>
                <a href="{% url 'products:about' %}">
                  About
                </a>
              </li>
              <li>
                <a href="{% url 'products:product' %}">
                  Products
                </a>
              </li>
              <li>
                <a href="{% url 'products:why' %}">
                  Why Us
                </a>
              </li>
              <li>
                <a href="{% url 'products:contact_us' %}">
                  contact us
                </a>
              </li>
            </ul>
          </div>
        </div>
        <div class="col-md-3">
          <div class="info_form ">
            <h5>
              Newsletter
            </h5>
            <form action="{% url 'orders:sendemail' %}" method="post">
              <input type="email" placeholder="Enter your email" name="email">
              <button>
                Subscribe
              </button>
            </form>
            <div class="social_box">
              <a href="https://wa.me/989376051315?text=I'm%20interested%20in%20chat" target="_blank">
                <i class="fa fa-whatsapp" aria-hidden="true"></i>
              </a>
              <a href="">
                <i class="fa fa-twitter" aria-hidden="true"></i>
              </a>
              <a href="">
                <i class="fa fa-instagram" aria-hidden="true"></i>
              </a>
              <a href="">
                <i class="fa fa-youtube" aria-hidden="true"></i>
              </a>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>

  <!-- end info_section -->


  <!-- footer section -->
  <footer class="footer_section">
    <div class="container">
      <p>
        &copy; <span id="displayYear"></span> All Rights Reserved By
        <b >SADAF SHOP</b>
      </p>
    </div>
  </footer>

templates/base/messages.html
{% if messages %}
    {% for msg in messages %}
        <p class="alert alert-{{ msg.tags }}">{{ msg }}</p>
    {% endfor %}
{% endif %}

templates/base/navbar.html
    <header class="header_section">
      <div class="header_top">
        <div class="container-fluid">
          <div class="top_nav_container">
            <div class="contact_nav">
              <a href="{% url 'products:contact_us' %}">
                <i class="fa fa-phone" aria-hidden="true"></i>
                <span>
                  Call : 09376051315
                </span>
              </a>
              <a href="{% url 'products:contact_us' %}">
                <i class="fa fa-envelope" aria-hidden="true"></i>
                <span>
                  Email : Alirezahn1@yahoo.com
                </span>
              </a>
            </div>
            <form class="search_form" method="post" action="{% url 'orders:searchproduct' %}">
                {% csrf_token %}
              <input type="search" required class="form-control" id="searchproducts" name="productsearch" placeholder="Search product">
              <button class="" type="submit">
                <i class="fa fa-search" aria-hidden="true"></i>
              </button>
            </form>
            <div class="user_option_box">
                {% if request.user.is_authenticated %}
                          <div class="nav-item dropdown">
        <a class="nav-link dropdown-toggle nav-item active" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            {{ request.user }}
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown" style="background-color: #248675">
          <a class="dropdown-item"  href="{% url 'customers:profile' %}">Profile</a>
          <a class="dropdown-item" href="{% url 'orders:myorders' %}">Orders</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="{% url 'customers:logout' %}">Logout</a>
        </div>
      </div>


            {% else %}
              <a  href="{% url 'customers:login' %}" class="account-link ">
                <i class="fa fa-user" aria-hidden="true"></i>
                <span>
                 Login
                </span>
              </a>
                {% endif %}
                {% if request.user.is_superuser or request.user.is_staff %}
                <a class="nav-item nav-link active" href="{% url 'admin:index' %}">Admin Panel</a>
                {% endif %}
              <a href="{% url 'orders:cart' %}" class="cart-link">
                <i class="fa fa-shopping-cart" aria-hidden="true"></i>
                <span>
                  Cart
                </span>
              </a>
                          <a href="{% url 'orders:wishlist' %}" class="cart-link">
                <i class="fa fa-heart" aria-hidden="true"></i>
                <span>
                  Whislist
                </span>
              </a>
            </div>
          </div>

        </div>
      </div>
      <div class="header_bottom">
        <div class="container-fluid">
          <nav class="navbar navbar-expand-lg custom_nav-container ">
            <h1 class="navbar-brand" href="home.html">
              <span>
               SADAF SHOP
              </span>
            </h1>

            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
              <span class=""> </span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
              <ul class="navbar-nav ">
                <li class="nav-item {% if request.resolver_match.url_name == 'home' %} active{% endif %} ">
                  <a class="nav-link " id="home" href="{% url 'products:home' %}" >Home <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item {% if request.resolver_match.url_name == 'about' %} active{% endif %}">
                  <a class="nav-link " id="about" href="{% url 'products:about' %}"> About</a>
                </li>
                <li class="nav-item {% if request.resolver_match.url_name == 'product' %} active{% endif %}">
                  <a class="nav-link" id="products" href="{% url 'products:product' %}">Products</a>
                </li>
                <li class="nav-item {% if request.resolver_match.url_name == 'why' %} active{% endif %}">
                  <a class="nav-link" id="why" href="{% url 'products:why' %}">Why Us</a>
                </li>
                <li class="nav-item {% if request.resolver_match.url_name == 'contact_us' %} active{% endif %}">
                  <a class="nav-link" id="contact" href="{% url 'products:contact_us' %}">contact us</a>
                </li>
              </ul>
            </div>
          </nav>
        </div>
      </div>
    </header>

templates/base/why.html
{% extends 'base/base.html' %}
{% load static %}
{% block title %}Why Us{% endblock %}
  <!-- about section -->
{% block content %}

  <!-- why us section -->

  <section class="why_us_section layout_padding" id="why">
    <div class="container">
      <div class="heading_container heading_center">
        <h2>
          Why Choose Us
        </h2>
      </div>
      <div class="row">
        <div class="col-md-4">
          <div class="box ">
            <div class="img-box">
              <img src="{% static 'images/w1.png'%}" alt="">
            </div>
            <div class="detail-box">
              <h5>
                Fast Delivery
              </h5>
              <p>
                variations of passages of Lorem Ipsum available
              </p>
            </div>
          </div>
        </div>
        <div class="col-md-4">
          <div class="box ">
            <div class="img-box">
              <img src="{% static 'images/w2.png'%}" alt="">
            </div>
            <div class="detail-box">
              <h5>
                Free Shiping
              </h5>
              <p>
                variations of passages of Lorem Ipsum available
              </p>
            </div>
          </div>
        </div>
        <div class="col-md-4">
          <div class="box ">
            <div class="img-box">
              <img src="{% static 'images/w3.png'%}" alt="">
            </div>
            <div class="detail-box">
              <h5>
                Best Quality
              </h5>
              <p>
                variations of passages of Lorem Ipsum available
              </p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
<section class="client_section layout_padding">
    <div class="container">
      <div class="heading_container heading_center">
        <h2>
          What Says Our Customers
        </h2>
      </div>
    </div>
    <div class="client_container ">
      <div id="carouselExample2Controls" class="carousel slide" data-ride="carousel">
        <div class="carousel-inner">
          <div class="carousel-item active">
            <div class="container">
              <div class="box">
                <div class="detail-box">
                  <p>
                    <i class="fa fa-quote-left" aria-hidden="true"></i>
                  </p>
                  <p>
                    It is a long established fact that a reader will be distracted by the readable content of a page
                    when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal
                    distribution of letters, as opposed to using 'Content here, content here', making it lookIt is a
                    long established fact that a reader will be distracted by the readable content of a page when
                    looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal
                    distribution of letters, as opposed to using 'Content here, content here', making it look
                  </p>
                </div>
                <div class="client-id">
                  <div class="img-box">
                    <img src="{% static 'images/client.jpg'%}" alt="">
                  </div>
                  <div class="name">
                    <h5>
                      James Dew
                    </h5>
                    <h6>
                      Photographer
                    </h6>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div class="carousel-item">
            <div class="container">
              <div class="box">
                <div class="detail-box">
                  <p>
                    <i class="fa fa-quote-left" aria-hidden="true"></i>
                  </p>
                  <p>
                    It is a long established fact that a reader will be distracted by the readable content of a page
                    when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal
                    distribution of letters, as opposed to using 'Content here, content here', making it lookIt is a
                    long established fact that a reader will be distracted by the readable content of a page when
                    looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal
                    distribution of letters, as opposed to using 'Content here, content here', making it look
                  </p>
                </div>
                <div class="client-id">
                  <div class="img-box">
                    <img src="{% static 'images/client.jpg'%}" alt="">
                  </div>
                  <div class="name">
                    <h5>
                      James Dew
                    </h5>
                    <h6>
                      Photographer
                    </h6>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div class="carousel-item">
            <div class="container">
              <div class="box">
                <div class="detail-box">
                  <p>
                    <i class="fa fa-quote-left" aria-hidden="true"></i>
                  </p>
                  <p>
                    It is a long established fact that a reader will be distracted by the readable content of a page
                    when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal
                    distribution of letters, as opposed to using 'Content here, content here', making it lookIt is a
                    long established fact that a reader will be distracted by the readable content of a page when
                    looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal
                    distribution of letters, as opposed to using 'Content here, content here', making it look
                  </p>
                </div>
                <div class="client-id">
                  <div class="img-box">
                    <img src="{% static 'images/client.jpg'%}" alt="">
                  </div>
                  <div class="name">
                    <h5>
                      James Dew
                    </h5>
                    <h6>
                      Photographer
                    </h6>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div class="carousel_btn-box">
          <a class="carousel-control-prev" href="#carouselExample2Controls" role="button" data-slide="prev">
            <span>
              <i class="fa fa-angle-left" aria-hidden="true"></i>
            </span>
            <span class="sr-only">Previous</span>
          </a>
          <a class="carousel-control-next" href="#carouselExample2Controls" role="button" data-slide="next">
            <span>
              <i class="fa fa-angle-right" aria-hidden="true"></i>
            </span>
            <span class="sr-only">Next</span>
          </a>
        </div>
      </div>
    </div>
  </section>
  <!-- end why us section -->

 {% endblock %}