Ecommerce/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('api/v1/', include('djoser.urls')),
    # path('api/v1/', include('djoser.urls.authtoken')),
    path('', include('orders.urls', namespace='orders')),
    path('', include('customers.urls',namespace='customers')),
    path('', include('products.urls',namespace='products')),

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

customers/urls.py
from django.urls import path


from .views import *
app_name = 'customers'

urlpatterns = [
    path('register/',UserRegisterView.as_view(),name='register'),
    path('login/', UserLoginView.as_view(), name='login'),
    path('logout/', UserLogoutView.as_view(), name='logout'),
    path('profile/', UserEditView.as_view(), name='profile'),
    path('changepassword/', change_password, name='changepassword'),

]

orders/urls.py
from django.urls import path
from .views import *


app_name = 'orders'



urlpatterns = [
    path('add-to-cart/',addtocart,name='addtocart'),
    path('cart/', viewcart, name='cart'),
    path('update-cart/',updatecart,name='updatecart'),
    path('delete-cart-item/',deletecartitem,name='deletecartitem'),
    path('add-to-wishlist/', addtowishlist, name='addtowishlist'),
    path('wishlist', wishlistview, name='wishlist'),
    path('delete-wishlist-item/',deletewishlistitem,name='deletewishlistitem'),
    path('checkout', checkout, name='checkout'),
    path('place-order', placeorder, name='placeorder'),
    path('my-orders', myorders, name='myorders'),
    path('orderview/<str:pk>/', orderview, name='orderview'),
    path('product-list/', productlist, name='productlist'),
    path('searchproduct/', searchproduct, name='searchproduct'),
    path('send-email/', send_email, name='sendemail'),
]

customers/models.py
from django.db import models

# Create your models here.
from core.models import User, BaseModel


class Customer(BaseModel):
    user = models.OneToOneField(User, models.CASCADE,primary_key=True )

    def __str__(self):
        return self.user.phone

class Address(BaseModel):
    customer = models.ForeignKey(Customer,on_delete=models.SET_NULL,null=True,blank=True)
    city = models.CharField(max_length=200)
    province = models.CharField(max_length=200)
    description = models.TextField(max_length=1000)
    home_plate = models.CharField(max_length=3)
    postal_code = models.CharField(max_length=10,help_text='Enter 10 digits')

    class Meta:
        verbose_name_plural = ('addresses')


    def __str__(self):
        return self.customer.user.phone

customers/views.py
from django.contrib.auth import authenticate, login, logout, update_session_auth_hash
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import PasswordChangeForm

from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import ValidationError
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse_lazy

from core.models import User
# Create your views here.
from django.views import View
from django.contrib import messages
from core.forms import UserCreationForm, UserLoginForm, UserChangeForm

from customers.models import Customer


class UserRegisterView(View):
    def post(self,request):
        if request.method == 'POST':
            form = UserCreationForm(request.POST)
            if form.is_valid():
                user = form.save(commit=False)
                user.save()
                customer = Customer.objects.create(user=user)
                customer.save()
                messages.success(request, 'successfully registered', 'success')
                return redirect('customers:login')
            else:
                messages.error(request, 'Please correct the error below.')
                return render(request, 'customer/register.html', {'form': form})
    def get(self,request):
        form = UserCreationForm()
        return render(request, 'customer/register.html', {'form': form})


class UserLoginView(View):
    def post(self,request):
        if request.method == 'POST':
            form = UserLoginForm(request.POST)

            if form.is_valid():
                cd = form.cleaned_data
                user = authenticate(request, phone=cd['phone'], password=cd['password'])
                if user is not None:
                    login(request, user)
                    messages.success(request, 'You logged in successfully', 'success')
                    return redirect('products:home')
                else:

                    messages.error(request, 'phone or password is wrong', 'danger')
                    return redirect('customers:login')
    def get(self,request):
        if request.user.is_authenticated:
            messages.warning(request,'You are already logged in !!')
            return redirect('products:home')
        else:
            form = UserLoginForm()
            return render(request, 'customer/login.html', {'form': form})



class UserLogoutView(LoginRequiredMixin,View):
    login_url = '/login/'
    redirect_field_name = 'login'
    def get(self,request):
        logout(request)
        messages.success(request, 'you logged out successfully', 'success')
        return redirect('products:home')

from django.views import generic

class UserEditView(LoginRequiredMixin,generic.UpdateView):
    login_url = '/login/'
    redirect_field_name = 'login'
    form_class = UserChangeForm
    template_name = 'customer/profile.html'
    success_url = reverse_lazy('products:home')

    def get_object(self, queryset=None):
        return self.request.user

def change_password(request):
    if request.method == 'POST':
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)  # Important!
            messages.success(request, 'Your password was successfully updated!')
            return redirect('products:home')
        else:
            messages.error(request, 'Please correct the error below.')
    else:
        form = PasswordChangeForm(request.user)
    return render(request, 'customer/changepassword.html', {
        'form': form
    })

templates/customer/changepassword.html
{% extends 'base/base.html' %}
{% block title %} Change password {% endblock %}
{% block content %}
  <div class="container" style="margin: 30px">
        <div class="row ">
    <div class="col-md-6">
        <div class="form-group-lg">
            <div class="card shadow  ">
                <div class="card-body">
    <h1>Change Password </h1> <br>



    <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class=" mt-2">
                        <label for="">Old password</label><br>
                        {{ form.old_password }}
                    </div>
        <div class="  mt-2">
                        <label for="">New password </label> <br>
                       {{ form.new_password1 }}
                        {{ form.new_password1.help_text }}
                    </div>
        <div class="  mt-2">
                        <label for="">New password confirmation </label>
                       {{ form.new_password2 }}
                    </div>
        <br>
                     {% if form.errors %}
        <div class="card border bg-gradient-info">
        {{ form.errors }}
        </div>
                     {% endif %}
        <br>
        <input type="submit"  class="btn btn-primary float-right" value="Confirm">
    </form>
        </div>
    </div>
    </div>
    </div>
    </div>
    </div>
{% endblock %}

templates/customer/login.html
{% extends 'base/base.html' %}
{% block title %} Login {% endblock %}
{% block content %}
            {% if form.errors %}
       {% for field in form %}
           {% for error in field.errors %}
              <div class="alert alert-danger">
                   <strong>{{ form.errors }}</strong>
              </div>
           {% endfor %}
       {% endfor %}
    {% endif %}
    <div class="container">
        <div class="row justify-content-center">
    <div class="col-md-6">
        <div class="">
        <div class="card mt-3 shadow">
            <div class="card-body">
                 <form action="" method="post" enctype="multipart/form-data">
                                         {% csrf_token %}
                     <div class="text-center">
                <h4>Login </h4>
                     </div> <hr>
        <div class="form-group">

        {{ form.as_p }}
        <br> <button type="submit"  class="btn btn-primary float-right shadow px-4"> Login </button>
     <br> <br> <hr>
    <h5 style="text-align: center;text-transform: capitalize">Don't have an account?<a href="{% url 'customers:register' %}">Register</a></h5>
        </div>
            </form>
            </div>
        </div>
        </div>
    </div>
        </div>
    </div>
{% endblock %}

templates/customer/profile.html
{% extends 'base/base.html' %}
{% block title %} Edit profile {% endblock %}
{% block content %}

    <div class="container" style="margin: 30px">
        <div class="row ">
    <div class="col-md-6">
        <div class="form-group-lg">
            <div class="card shadow  ">
                <div class="card-body">
    <h1>Edit profile </h1> <br>



    <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}

        <a href="{% url 'customers:changepassword' %}"> Change Password</a> <br>
        <input type="submit"  class="btn btn-primary float-right" value="Update">
    </form>
        </div>
    </div>
    </div>
    </div>
    </div>
    </div>





{% endblock %}

templates/customer/register.html
{% extends 'base/base.html' %}
{% block title %} Register {% endblock %}
{% block content %}

    <div class="container">
        <div class="row justify-content-center">
    <div class="col-md-6">
        <div class="card mt-3 shadow">
            <div class="card-body">
                 <form action="" method="post" enctype="multipart/form-data">
                     {% csrf_token %}
                     <div class="text-center">
                <h4>Register </h4>
                     </div> <hr>
            <div class="form-group mt-2">
                <label for=""> Phone :</label>
                {{ form.phone }}
            </div>
                     <div class="form-group mt-2">
                <label for=""> Email :</label>
                {{ form.email }}
            </div>
                      <div class="form-group mt-2">
                <label for=""> First Name :</label>
                {{ form.first_name }}
            </div>
            <div class="form-group mt-2">
                <label for=""> Last Name :</label>
                {{ form.last_name }}
            </div>
                    <div class="form-group mt-2">
                <label for=""> Password :</label>
                {{ form.password1 }}

            </div>
                            <div class="form-group mt-2">
                <label for=""> Confirm Password :</label>
                {{ form.password2 }}


            </div>
                     <br>
                                          {% if form.errors %}
        <div class="card border bg-gradient-info">
        {{ form.errors }}
        </div>
                     {% endif %}
                     <button type="submit"  class="btn btn-primary float-right shadow px-4"> Register </button>


    </form>

        </div>
        </div>
    </div>
    </div>
    </div>
{% endblock %}