Ecommerce/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('api/v1/', include('djoser.urls')),
    # path('api/v1/', include('djoser.urls.authtoken')),
    path('', include('orders.urls', namespace='orders')),
    path('', include('customers.urls',namespace='customers')),
    path('', include('products.urls',namespace='products')),

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orders/urls.py
from django.urls import path
from .views import *


app_name = 'orders'



urlpatterns = [
    path('add-to-cart/',addtocart,name='addtocart'),
    path('cart/', viewcart, name='cart'),
    path('update-cart/',updatecart,name='updatecart'),
    path('delete-cart-item/',deletecartitem,name='deletecartitem'),
    path('add-to-wishlist/', addtowishlist, name='addtowishlist'),
    path('wishlist', wishlistview, name='wishlist'),
    path('delete-wishlist-item/',deletewishlistitem,name='deletewishlistitem'),
    path('checkout', checkout, name='checkout'),
    path('place-order', placeorder, name='placeorder'),
    path('my-orders', myorders, name='myorders'),
    path('orderview/<str:pk>/', orderview, name='orderview'),
    path('product-list/', productlist, name='productlist'),
    path('searchproduct/', searchproduct, name='searchproduct'),
    path('send-email/', send_email, name='sendemail'),
]

products/urls.py
from django.urls import path
app_name = 'products'

from .views import *

urlpatterns = [
    path('',HomeView.as_view(),name='home'),
    path('about/',AboutView.as_view(),name='about'),
    path('product/',ProductView.as_view(),name='product'),
    path('why/',WhyView.as_view(),name='why'),
    path('contact_us/',contact,name='contact_us'),
    path('<str:prod_slug>/', productview, name='product_detail'),
    path('category/<slug:slug>/', ProductView.as_view(), name='category_filter'),




]

orders/models.py
from django.db import models
from core.models import BaseModel
# Create your models here.
from customers.models import Customer, Address
from products.models import Product, AbstractDiscount
from core.models import User

class OffCode(AbstractDiscount):
    code = models.CharField(max_length=15, unique=True)


class Order(BaseModel):
    customer = models.ForeignKey(Customer,on_delete=models.RESTRICT,related_name='orders')
    address = models.ForeignKey(Address, on_delete=models.RESTRICT)
    off_code = models.ForeignKey(OffCode, on_delete=models.SET_NULL, null=True, blank=True)
    paid = models.BooleanField(default=False)
    total_price = models.IntegerField(null=True)


    class Meta:
        unique_together = [['off_code', 'customer']]
        ordering = ('-created',)

    def __str__(self):
        return f'{self.customer} - {str(self.id)}'

    # def get_total_price(self):
    #     total = sum(item.get_cost() for item in self.items.all())
    #     if self.off_code:
    #         discount_price = (self.off_code / 100) * total
    #         return int(total - discount_price)
    #     return total

class OrderItem(BaseModel):
    product = models.ForeignKey(Product, on_delete=models.RESTRICT)
    order = models.ForeignKey(Order, on_delete=models.RESTRICT)
    quantity = models.PositiveIntegerField(null=True)

    def __str__(self):
        return str(self.id)

    def get_cost(self):
        return self.product.price * self.quantity

class Cart(BaseModel):
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    product_qty = models.IntegerField(null=False,blank=False)

orders/forms.py
from django import forms


class CartAddForm(forms.Form):
    amount = forms.IntegerField(min_value=1)

orders/views.py
from django.core.mail import send_mail, BadHeaderError
from django.http import JsonResponse, HttpResponse, HttpResponseRedirect
from django.shortcuts import render, redirect
from django.views.generic import ListView
from django.contrib.auth.decorators import login_required
from products.models import Product, Wishlist
from .models import *
from customers.urls import *

# Create your views here.
from django.views.decorators.csrf import csrf_exempt


@csrf_exempt
def addtocart(request):
    if request.method == 'POST':
        if request.user.is_authenticated:
            prod_id = int(request.POST.get('product_id'))
            product_check = Product.objects.get(id=prod_id)
            if product_check:
                if Cart.objects.filter(user=request.user.id, product_id=prod_id):
                    return JsonResponse({'status': "Product Already in Cart"})
                else:
                    prod_qty = int(request.POST.get('product_qty'))

                    if product_check.quantity >= prod_qty:
                        Cart.objects.create(user=request.user, product_id=prod_id, product_qty=prod_qty)
                        return JsonResponse({'status': "Product Added successfully"})
                    else:
                        return JsonResponse({'status': "Only  " + str(product_check.quantity) + "quantity available"})
            else:
                return JsonResponse({'status': "No such product found"})


        else:
            return JsonResponse({'status': "login to Continue"})

    return redirect('products:home')


@login_required(login_url='customers:login')
def viewcart(request):
    cart = Cart.objects.filter(user=request.user)
    context = {'cart': cart}
    return render(request, 'orders/cart.html', context)


@csrf_exempt
def updatecart(request):
    if request.method == 'POST':
        prod_id = int(request.POST.get('product_id'))
        if Cart.objects.filter(user=request.user, product_id=prod_id):
            prod_qty = int(request.POST.get('product_qty'))
            cart = Cart.objects.get(product_id=prod_id, user=request.user)
            cart.product_qty = prod_qty
            cart.save()
            return JsonResponse({'status': "Updated Successfully"})
    return redirect('products:home')


@csrf_exempt
def deletecartitem(request):
    if request.method == 'POST':
        prod_id = int(request.POST.get('product_id'))
        if Cart.objects.filter(user=request.user, product_id=prod_id):
            cartitem = Cart.objects.get(product_id=prod_id, user=request.user)
            cartitem.delete()
        return JsonResponse({'status': "Deleted Successfully"})
    return redirect('products:home')


@csrf_exempt
def addtowishlist(request):
    if request.method == 'POST':
        if request.user.is_authenticated:
            prod_id = int(request.POST.get('product_id'))
            product_check = Product.objects.get(id=prod_id)
            if product_check:
                if Wishlist.objects.filter(user=request.user, product_id=prod_id):
                    return JsonResponse({'status': "Product Already in Wishlist"})
                else:
                    Wishlist.objects.create(user=request.user, product_id=prod_id)
                    return JsonResponse({'status': "Product Added to Wishlist"})


            else:
                return JsonResponse({'status': "No such product found"})

        else:
            return JsonResponse({'status': "login to Continue"})

    return redirect('products:home')

@login_required(login_url='customers:login')
def wishlistview(request):
    wishlist = Wishlist.objects.filter(user=request.user)
    context ={'wishlist':wishlist}
    return render(request,'products/wishlist.html',context)

@csrf_exempt
def deletewishlistitem(request):
    if request.method == 'POST':
        if request.user.is_authenticated:
            prod_id = int(request.POST.get('product_id'))
            if Wishlist.objects.filter(user=request.user, product_id=prod_id):
                whishitem = Wishlist.objects.get(product_id=prod_id, user=request.user)
                whishitem.delete()
                return JsonResponse({'status': "Product removed from Wishlist Successfully"})
            else:
                return JsonResponse({'status': "Product not found in wishlist"})
        else:
            return JsonResponse({'status': "login to Continue"})
    return redirect('products:home')

@login_required(login_url='customers:login')
def checkout(request):
    rawcart = Cart.objects.filter(user=request.user)
    for item in rawcart:
        if item.product_qty > item.product.quantity:
            Cart.objects.delete(id=item.id)

    cartitems = Cart.objects.filter(user=request.user)
    total_price = 0
    for item in cartitems:
        if item.product.discount:
            total_price = total_price + item.product.final_price() * item.product_qty
        else:
            total_price = total_price + item.product.price * item.product_qty


    context = {'cartitems':cartitems,'total_price':total_price}
    return render(request,'orders/checkout.html',context)

@login_required(login_url='customers:login')
@csrf_exempt
def placeorder(request):
    if request.method == 'POST':
        neworder = Order()
        customer = Customer.objects.get(user=request.user)
        neworder.customer = customer
        newaddress =Address.objects.create(customer=customer,city=request.POST.get('city'),province=request.POST.get('province')
                                           ,description=request.POST.get('address'),home_plate=request.POST.get('plate')
                                           ,postal_code=request.POST.get('code'))
        neworder.address = newaddress
        cart = Cart.objects.filter(user=request.user)
        total_price = 0
        for item in cart:
            if item.product.discount:
                total_price = total_price + item.product.final_price() * item.product_qty
            else:
                total_price = total_price + item.product.price * item.product_qty

        neworder.total_price = total_price
        neworder.paid = True
        neworder.save()
        neworderitem = Cart.objects.filter(user=request.user)
        for item in neworderitem :
            OrderItem.objects.create(
                order=neworder,
                product=item.product,
                quantity=item.product_qty
            )
            orderproduct = Product.objects.filter(id=item.product_id).first()
            orderproduct.quantity = orderproduct.quantity - item.product_qty
            orderproduct.save()

        Cart.objects.filter(user=request.user).delete()
        messages.success(request, 'your order has been placed successfully')

    return redirect('products:home')


def myorders(request):
    customers = Customer.objects.get(user=request.user)
    orders = Order.objects.filter(customer=customers)
    context = {'orders': orders}
    return render(request,'orders/myorders.html',context)

def orderview(request,pk):
    customer = Customer.objects.get(user=request.user)
    order = Order.objects.filter(customer=customer).filter(id=pk).first()
    orderitems = OrderItem.objects.filter(order=order)
    context = {'order':order,'orderitems':orderitems}
    return render(request,'orders/view.html',context)

def productlist(request):
    products = Product.objects.filter(available=True).values_list('name',flat=True)
    productslist = list(products)
    return JsonResponse(productslist,safe=False)

@csrf_exempt
def searchproduct(request):
    if request.method == 'POST':
        searched = request.POST.get('productsearch')
        if searched == '':
            return redirect(request.META.get('HTTP_REFERER'))
        else:
            product = Product.objects.filter(name__contains= searched).first()
            if product:
                return redirect(product.get_absolute_url())
            else:
                messages.info(request,'No product matched your search')
                return redirect(request.META.get('HTTP_REFERER'))


    return redirect(request.META.get('HTTP_REFERER'))

from django.conf import settings
@csrf_exempt
def send_email(request):
    if request.method == 'POST':
        email = list(request.POST.get('email'))
        if email:
            try:
                # send_mail('Joined Newsletter', 'We will send you our news',settings.EMAIL_HOST_USER , email)
                messages.info(request, 'Thank you for join!!')

            except BadHeaderError:
                return HttpResponse('Invalid header found.')
            return redirect('products:home')
        else:
            # In reality we'd use a form class
            # to get proper validation errors.
            return redirect('products:home')

templates/orders/cart.html
{% extends 'base/base.html' %}
{% block title %}Cart {% endblock %}

{% block content %}

    <div class="py-5">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="card shadow ">
                        <div class="card-body cartdata">
                            {% if cart %}
                                {% for item in cart %}
                                <div class="row product_data">
                                    <div class="col-md-2 my-auto">
                                        <img src="{{ item.product.image.url }}" alt="{{ item.product.name }}" height="70px" width="70px">
                                    </div>
                                    <div class="col-md-3 my-auto">
                                        <a href="{% url 'products:product_detail' item.product.slug  %}">{{ item.product.name }}</a>
                                    </div>
                                    <div class="col-md-2 my-auto">
                                        <h6>{% if item.product.discount %}{{ item.product.final_price | stringformat:'d' }} {% else %}$ {{ item.product.price }}{% endif %} </h6>
                                    </div>
                                    <div class="col-md-3 my-auto">
                                        <input type="hidden" class="prod_id" value="{{ item.product_id }}">
                                        {% csrf_token %}
                                        {% if item.product.quantity >= item.product_qty %}
                                            <label for="Quantity">Quantity</label>
                                            <div class="input-group text-center mb-3" style="width: 130px;">
                                            <button class="input-group-text changeQuantity decrement-btn">-</button>
                                            <input type="text" name="quantity" class="form-control qty-input text-center" value={{ item.product_qty }}>
                                            <button class="input-group-text  changeQuantity increment-btn">+</button>
                                    </div>
                                            {% else %}
                                            <h6> Out of Stock</h6>
                                            {% endif %}
                                </div>
                                    <div class="col-md-2 my-auto">
                                    <button class="btn btn-danger delete-cart-item"><i class="fa fa-trash"></i> Remove</button>
                                    </div>
                                </div>

                            {% endfor %}
                                <a href="{% url 'orders:checkout' %}" class="btn btn-outline-success float-right"> Checkout</a>
                            {% else %}
                            <h4> Your cart is empty</h4>
                            {% endif %}

                        </div>

                    </div>
                </div>

            </div>

        </div>

    </div>



{% endblock %}

templates/orders/checkout.html
{% extends 'base/base.html' %}
{% block title %}Checkout {% endblock %}
{% block style %}
    .checkoutform label {
    font-size: 16px !important;
    font-weight:600
    }

{% endblock %}
{% block content %}

<div class="container mt-3 mb-3">
    <form action="{% url 'orders:placeorder' %}" method="POST">
    {% csrf_token %}
    <div class="row">
        <div class="col-md-7">
            <div class="card shadow ">
                <div class="card-body">
                    <h6 style="font-size: 18px;font-weight: 600">Basic Details</h6>
                    <hr>
                    <div class="row checkoutform">
                        <div class="col-md-6 mt-2">
                        <label for="">First Name</label>
                        <input type="text" required class="form-control" value="{{ request.user.first_name }}" name="fname" placeholder="Enter First Name">
                    </div>
                        <div class="col-md-6 mt-2">
                        <label for="">Last Name</label>
                        <input type="text" required class="form-control"  value="{{ request.user.last_name }}" name="lname" placeholder="Enter Last Name">
                    </div>
                        <div class="col-md-6 mt-2">
                        <label for="">Email</label>
                        <input type="text" required class="form-control" value="{{ request.user.email }}" name="email" placeholder="Enter Email">
                    </div>
                        <div class="col-md-6 mt-2">
                        <label for="">Phone</label>
                        <input type="text" required class="form-control"  value="{{ request.user.phone }}" name="phone" placeholder="Enter Phone">
                    </div>
                        <div class="col-md-6 mt-2">
                        <label for="">Province</label>
                        <input type="text" required class="form-control" name="province" placeholder="Enter Province">
                    </div>
                        <div class="col-md-6 mt-2">
                        <label for="">City</label>
                        <input type="text" required class="form-control" name="city" placeholder="Enter City">
                    </div>
                        <div class="col-md-12 mt-2">
                        <label for="">Address</label>
                            <textarea type="text" required class="form-control" name="address" placeholder="Enter Address"></textarea>
                    </div>
                        <div class="col-md-6 mt-2">
                        <label for="">Home Plate</label>
                        <input type="text" required class="form-control" name="plate" placeholder="Enter Home Plate">
                    </div>
                       <div class="col-md-6 mt-2">
                        <label for="">Postal Code</label>
                        <input type="text" required class="form-control" name="code" placeholder="Enter Postal Code">
                    </div>
                        </div>
                </div>

            </div>
        </div>


    <div class="col-md-5">
        <div class="card shadow">
            <div class="card-body">
                <h6 style="font-size: 18px;font-weight: 600">Order Summary</h6>
                <hr>
                {% if cartitems %}
                    <table class="table table-striped table-borderless">
                    <thead>
                        <tr>
                            <th> Product</th>
                            <th> Qty</th>
                            <th> Price</th>

                        </tr>
                    </thead>
                    <tbody>
                        {% for item in cartitems %}
                            <tr>
                                <td><img src="{{ item.product.image.url }}" alt="" height="50px" width="50px" class="me-2">{{ item.product.name }}</td>

                                <td> {{ item.product_qty }}</td>
                            {% if item.product.discount %}
                                <td>{{ item.product.final_price | stringformat:'d' }}</td>

                            {% else %}
                            <td> {{ item.product.price | stringformat:'d' }}</td>
                            </tr>
                            {% endif %}
                        {% endfor %}

                    </tbody>
                    </table>

                    <div class="card-body">
                        <form>
                            <div class="form-group"> <label>Have coupon?</label>
                                <div class="input-group"> <input type="text" class="form-control coupon" name="" placeholder="Coupon code"> <span class="input-group-append"> <button class="btn btn-primary btn-apply coupon">Apply</button> </span> </div>
                            </div>
                        </form>
                    </div>

                    <h6 class="text-bold float-right mt-3" style="font-weight: 600">Grand Total
                    <span> $ {{ total_price | stringformat:'d' }} </span></h6>
                    <div class="mt-3">
                        <button  type="submit" class="btn btn-success w-100"> Payment</button>
                    </div>
                {% else %}
                    <h4> Your Cart is empty</h4>
                {% endif %}
            </div>
        </div>
    </div>
</div>
    </form>
</div>


{% endblock %}

templates/orders/items.html
{% extends 'base/base.html' %}
{% block title %}cart {% endblock %}
{% block style %}
        .loading {
            position: fixed;
            top: 0;
            bottom: 0;
            right: 0;
            left: 0;
            display: flex;
            justify-content: center;
            align-items: center;
        }

        .text {
            font-size: 72px;
            text-align: center;

        }

        .blur-bg {
            position: fixed;
            top: 0;
            bottom: 0;
            right: 0;
            left: 0;
            background: rgba(0, 0, 0, 0.26);
            filter: blur(2px);
        }
{% endblock %}
{% block content %}
<div class="loading" style="display: none">
    <div class="text"><i class="gb gb_replay gb_animate_spin"></i></div>
</div>
    <h1></h1>
<center>
    {% for item in items %}
        <div item-id="{{ item.id }}">{{ item.product.name }} | <input type="number" name="quantity"
                                                                      value="{{ item.quantity }}" min="1"> | <a
                style="color: red ; cursor: pointer" class="delete-key">Delete</a>
            <hr>
        </div>

    {% endfor %}
</center>
<script>
    $(document).ajaxStart(function () {
        $('center').attr('class', 'blur-bg')
        $('.loading').fadeIn()
    })
    $(document).ajaxStop(function () {
        $('center').attr('class', '')
        $('.loading').fadeOut()
    })
    $('input[name=quantity]').on('change', function () {
        let count = $(this).val()
        let item_id = $(this).parent().attr('item-id')

        $.ajax({
            method: 'PATCH',
            url: "{% url 'orders:order_item' 0 %}".replace('0', item_id),
            data: {
                'quantity': count
            },
            headers: {
                'X-CSRFToken': '{{ csrf_token }}'
            }
        })
    })

    $('a[class=delete-key]').on('click', function () {
        let parent = $(this).parent()
        let item_id = parent.attr('item-id')
        $.ajax({
            type: 'DELETE',
            url: "{% url 'orders:order_item' 0 %}".replace('0', item_id),
            headers: {
                'X-CSRFToken': '{{ csrf_token }}'
            },
            success: function () {
                parent.remove()
            }
        })
    })
</script>
{% endblock %}

templates/orders/myorders.html
{% extends 'base/base.html' %}
{% block title %}My Orders{% endblock %}

{% block content %}
<div class="container mt-3 mb-3">
    <div class="row">
        <div class="col-md-12">
            <div class="card shadow ">
            <div class="card-header"> <h3> My Orders</h3></div>
                <div class="card-body">
                    <table class="table table-bordered">
                        <thead>
                            <tr>
                                <th> Order Date</th>
                                <th> Total Price</th>
                                <th> Pay Status</th>
                                <th> Action</th>
                            </tr>
                        </thead>
                       <tbody>
                       {% for order in orders %}
                            <tr>
                                <td> {{ order.created }}</td>
                                <td> {{ order.total_price }}</td>
                                <td><span style="font-size: 20px">&#9989</span></td>
                                <td><a href="{% url 'orders:orderview' order.id %}" class="btn btn-primary"> View</a></td>
                            </tr>
                       {% endfor %}
                        </tbody>
                    </table>



            </div>
        </div>
</div>
    </div>
</div>

{% endblock %}

templates/orders/view.html
{% extends 'base/base.html' %}
{% block title %}Order View{% endblock %}

{% block content %}
<div class="container mt-3 mb-3">
    <div class="row">
        <div class="col-md-12">
            <div class="card shadow ">
            <div class="card-header">
                <h3 class="mb-0">Order View
                    <a href="{% url 'orders:myorders' %}" class="btn btn-warning float-right text-white"><i class="fa fa-reply"></i> Back</a>
            </h3></div>
                <div class="card-body">
                    <div class="row">
                        <div class="col-md-6">
                            <h4>Shopping Details</h4>
                            <hr>
                            <label class="mt-2" >First Name</label>
                            <div class="border p-1">{{ request.user.first_name }}</div>
                            <label class="mt-2" >Last Name</label>
                            <div class="border p-1">{{ request.user.last_name }}</div>
                            <label class="mt-2" >Email</label>
                            <div class="border p-1">{{ request.user.email }}</div>
                            <label class="mt-2" >Phone</label>
                            <div class="border p-1">{{ request.user.phone }}</div>
                            <label class="mt-2" >Province</label>
                            <div class="border p-1">{{ order.address.province }}</div>
                            <label class="mt-2" >City</label>
                            <div class="border p-1">{{ order.address.city }}</div>
                            <label class="mt-2">Address</label>
                            <div class="border p-1">{{ order.address.description }}</div>
                             <label class="mt-2">Home Plate</label>
                            <div class="border p-1">{{ order.address.home_plate }}</div>
                            <label class="mt-2">Postal Code</label>
                            <div class="border p-1">{{ order.address.postal_code }}</div>
                        </div>
                        <div class="col-md-6">
                            <h4>Order Details</h4>
                            <hr>
                            <table class="table table-bordered">
                                <thead>
                                    <tr>
                                        <th> Name</th>
                                        <th> Quantity</th>
                                        <th> Price</th>
                                        <th> Image</th>
                                    </tr>
                        </thead>
                       <tbody>
                       {% for item in orderitems %}
                            <tr>
                                <td> {{ item.product.name }}</td>
                                <td> {{ item.quantity }}</td>
                                <td>{{ item.product.price }}</td>
                                <td><img src="{{ item.product.image.url }}" height="70px" width="70px" alt="{{ item.product.name }}"></td>
                            </tr>
                       {% endfor %}
                        </tbody>
                    </table>
                        <h4 class="border p-2">Total Price :<span class="float-right"> ${{ order.total_price }}</span> </h4>
                        </div>
                    </div>


            </div>
        </div>
</div>
    </div>
</div>
{% endblock %}